cp template-minimal.yaml df-009.yaml
cp template-minimal.yaml df-010.yaml
cp template-minimal.yaml df-011.yaml
cp template-minimal.yaml df-012.yaml
cp template-minimal.yaml df-013.yaml
cp template-minimal.yaml df-014.yaml
cp template-minimal.yaml df-015.yaml
cp template-minimal.yaml df-016.yaml
cp template-minimal.yaml df-017.yaml
cp template-minimal.yaml df-018.yaml
cp template-minimal.yaml df-019.yaml
cp template-minimal.yaml df-020.yaml
cp template-minimal.yaml df-021.yaml
cp template-minimal.yaml df-022.yaml
cp template-minimal.yaml df-023.yaml
cp template-minimal.yaml df-024.yaml
cp template-minimal.yaml df-025.yaml
cp template-minimal.yaml df-026.yaml
cp template-minimal.yaml df-027.yaml
cp template-minimal.yaml df-028.yaml
cp template-minimal.yaml df-029.yaml
cp template-minimal.yaml df-030.yaml
cp template-minimal.yaml df-031.yaml
cp template-minimal.yaml df-043.yaml
cp template-minimal.yaml df-044.yaml
cp template-minimal.yaml df-045.yaml
cp template-minimal.yaml df-056.yaml
cp template-minimal.yaml df-047.yaml
cp template-minimal.yaml df-048.yaml
cp template-minimal.yaml df-049.yaml
cp template-minimal.yaml df-050.yaml
cp template-minimal.yaml df-101.yaml
cp template-minimal.yaml df-102.yaml
cp template-minimal.yaml df-103.yaml
cp template-minimal.yaml df-106.yaml
cp template-minimal.yaml df-108.yaml
cp template-minimal.yaml df-110.yaml
cp template-minimal.yaml df-111.yaml
cp template-minimal.yaml df-112.yaml
cp template-minimal.yaml df-113.yaml
cp template-minimal.yaml df-115.yaml
cp template-minimal.yaml df-116.yaml
cp template-minimal.yaml df-117.yaml
